In [1]:
import numpy as np 
from GNBG import GNBG

In [2]:
probs = GNBG(16)
f = probs.fitness_mfea

ID: 16
Optimal value:  -5000


In [3]:
def DeltaDifference(X1, X2, f):
    P1 = np.array([0.0]*probs.dim)
    P2 = P1.copy()
    P2[X1] = 1
    delta1 = f(P2) - f(P1)
    P3 = P1.copy()
    P4 = P2.copy()
    P3[X2] = 0.5
    P4[X2] = 0.5
    delta2 = f(P4) - f(P3)
    diff = abs(delta1 - delta2)
    return diff


In [4]:
def detect_interdependent_variables(n, f):
    status = [0] * n
    dim = list(range(0, n))

    epsilon = 1e-5  # small positive number

    for k in range(n):
        X1 = k
        X2 = [x for x in dim if x != X1]
        diff = DeltaDifference(X1, X2, f)

        if diff > epsilon:
            status[k] = 1

    return status



In [5]:
def build_interaction_matrix(n, f, status):
    k = 0
    status_c = status.copy()
    status_r = status.copy()
    Omega = np.zeros((n, n))
    epsilon = 1e-5 
    for i in range(n):
        if status_r[i] == 1:
            k += 1
            for j in range(n):
                if status_c[j] ==1:
                    X1 = i
                    X2 = j
                    diff = DeltaDifference(X1,X2,f)
                    if diff > epsilon:
                        Omega[i,j] = 1
                        status_r[j] = 0
    return Omega

In [6]:
status = detect_interdependent_variables(16, f)
Omega = build_interaction_matrix(16, f, status)
print(Omega)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
def perturb(genes, d, r0):
    sample_genes = genes.copy()
    sample_genes[d] += np.random.uniform(-r0, r0)
    return sample_genes

In [37]:
def brute_force_localsearch(f, genes):
    r0 = 0.01
    fit = f(genes)
    for j in range(100):
        for d in range(len(genes)):
            new_genes1 = genes.copy()
            new_genes2 = genes.copy()
            new_genes1[d] = genes[d] + r0
            new_genes2[d] = genes[d] - r0
            if f(new_genes1) < fit or f(new_genes2) < fit:
                print("Success")
                break
        r0 += 0.05
    print("End because end of iter")



In [92]:
from scipy.optimize import fmin_l_bfgs_b
sol, fit, info = fmin_l_bfgs_b(f, np.random.rand(30), approx_grad=True, bounds=[(0,1)]*30, maxfun = 1000, factr=10)
print(fit)

-4999.999999999976


In [49]:
fit

-4317.899999999976

In [50]:
sol

array([0.34186605, 0.41741397, 0.80249395, 0.21230955, 0.65385809,
       0.23586433, 0.52653222, 0.11463062, 0.73142346, 0.33022027,
       0.31243732, 0.57144443, 0.43134341, 0.8556758 , 0.74591303,
       0.70064968, 0.37911867, 0.63075319, 0.56271169, 0.10229626,
       0.3858158 , 0.65271753, 0.65745452, 0.6692198 , 0.29696885,
       0.19933865, 0.11491783, 0.79083348, 0.19707476, 0.54777358])

array([0.1000915 , 0.37644858, 0.2635618 , 0.54695186, 0.35073934,
       0.13124382, 0.86631162, 0.76770053, 0.32435519, 0.33489132,
       0.26930249, 0.21738286, 0.65552013, 0.51191128, 0.21142108,
       0.37821269, 0.70075395, 0.87187203, 0.45992971, 0.55894359,
       0.80875368, 0.84354978, 0.84607637, 0.83841962, 0.12264518,
       0.7736247 , 0.54882417, 0.41028851, 0.14793414, 0.67039118])

In [39]:
brute_force_localsearch(f, sol)

End because end of iter
